In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torchvision.transforms as transforms

In [2]:
a = np.random.rand(16,16) + 1j * np.random.rand(16,16)
# print(a)

In [7]:
loaded = np.load("/home/newfasant2/N101/N101-IA/Datasets/Raw/Samples_64_f_64_d/Scaneagle_UAV_50000_fixed_meters/sample_4_133.151340_P.npy")
a = loaded[:, :, 0] + 1j * loaded[:, :, 1]

fft_general = np.fft.fftshift(np.fft.fft2(a))
fft_perfil = np.fft.fftshift(np.fft.fft(a=a, axis=0))
plt.xticks([])
plt.yticks([])
plt.imsave("/home/newfasant2/N101/N101-IA/Datasets/" + "_4.png", arr=np.abs(fft_general), cmap="gray", format="png")
plt.close() # Close the figure to free memory

plt.xticks([])
plt.yticks([])
plt.imsave("/home/newfasant2/N101/N101-IA/Datasets/" + "_perfil_4.png", arr=np.abs(fft_perfil), cmap="gray", format="png")
plt.close() # Close the figure to free memory

In [4]:
prueb = np.random.rand(4,4)
new_prueb = np.zeros(shape=(8, 8))

In [5]:
for i in range(prueb.shape[0]):
    for j in range(prueb.shape[1]):
        new_prueb[2*i:2*(i+1), 2*j:2*(j+1)] = prueb[i, j]

In [6]:
print(prueb)
print(new_prueb)

[[0.50179218 0.44088283 0.75031633 0.41328426]
 [0.96136685 0.29532263 0.86740359 0.94082291]
 [0.53847334 0.26813291 0.49244944 0.76832983]
 [0.71954096 0.27316901 0.54698491 0.93798429]]
[[0.50179218 0.50179218 0.44088283 0.44088283 0.75031633 0.75031633
  0.41328426 0.41328426]
 [0.50179218 0.50179218 0.44088283 0.44088283 0.75031633 0.75031633
  0.41328426 0.41328426]
 [0.96136685 0.96136685 0.29532263 0.29532263 0.86740359 0.86740359
  0.94082291 0.94082291]
 [0.96136685 0.96136685 0.29532263 0.29532263 0.86740359 0.86740359
  0.94082291 0.94082291]
 [0.53847334 0.53847334 0.26813291 0.26813291 0.49244944 0.49244944
  0.76832983 0.76832983]
 [0.53847334 0.53847334 0.26813291 0.26813291 0.49244944 0.49244944
  0.76832983 0.76832983]
 [0.71954096 0.71954096 0.27316901 0.27316901 0.54698491 0.54698491
  0.93798429 0.93798429]
 [0.71954096 0.71954096 0.27316901 0.27316901 0.54698491 0.54698491
  0.93798429 0.93798429]]


In [40]:
import numpy as np
import random 
a = np.array([[1+2*1j, 3+4*1j], [0+3*1j, 2+1*1j]])
a.size
b=sum(sum(np.abs(a*a)))/a.size
b
c = np.abs(np.zeros_like(a))
c = np.random.normal(0,1,a.shape)
c
print(c)
print(sum(sum(c)))


[[-0.8123416  -0.13866095]
 [ 1.34243486 -0.70255279]]
-0.3111204729667283


In [38]:
pr = 0
if pr:
    print('enter')